apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-deployment2
  labels:
    app: custom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom
  template:
    metadata:
      labels:
        app: custom
    spec:
      containers:
      - name: custom
        image: dhananjay9/image2
        ports:
        - containerPort: 80
